### ISSUE TITLE
'runHtmlUrl' output is NOT mentioned in action.yaml so that it cannot be used

### ISSUE THREAD

**Issue by yanasazanavets** [phoenix-actions/test-reporting#10]
I am trying to use `runHtmlUrl` output in my workflow, however it is NOT possible since action.yaml does NOT have `runHtmlUrl` being listed

**Comment by lyona** [comment]
seems to work for me:
```
    - name: Publish Test Results
      uses: phoenix-actions/test-reporting@v6
      id: search-report
      with:
        name: ${{ github.workflow }} Search Test Report
        fail-on-error: 'true'
        path: tests/*.trx
        reporter: dotnet-trx

    - name: Write report url
      run: echo "::notice::${{ steps.search-report.outputs.runHtmlUrl }}"
      shell: bash
```
