### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by dkirrane** [phoenix-actions/test-reporting#18]
`Error: Cannot read properties of undefined (reading 'split')`

Hitting this with the following test results XML

```
    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      with:
        name: Terratest Tests
        path: report.xml
        reporter: java-junit
```

report.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="1" failures="1" time="0.000" name="Elvis">
		<properties>
			<property name="go.version" value="go1.17"></property>
		</properties>
		<testcase classname="Elvis" name="[build failed]" time="0.000">
			<failure message="Failed" type=""></failure>
		</testcase>
	</testsuite>
</testsuites>
```

It's a Junit XML file created by [Terratest](https://terratest.gruntwork.io/docs/testing-best-practices/debugging-interleaved-test-output/)
