### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by marauder2k7** [phoenix-actions/test-reporting#41]
Any way to fix this issue? 

Do i need to add some special permissions?

**Comment by djthornton1212** [comment]
@marauder2k7 Please take a look at this issue https://github.com/dorny/test-reporter/issues/168. 

They discuss the need for the following permissions:

```yaml
permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  actions: write
```
