### ISSUE TITLE
Test report randomly appears under different workflow

### ISSUE THREAD

**Issue by agracio** [phoenix-actions/test-reporting#60]
Unfortunately running into the same issue as https://github.com/phoenix-actions/test-reporting/issues/25. Test results of one workflow appear under another unrelated workflow if they are running relatively close together. Test result names are different.

Test runner runs on commit:
```yml
- name: Create test report
      uses: phoenix-actions/test-reporting@v15
      if: success()
      with:
        name: 'test-results-...matrix'
        fail-on-error: true
        path: mochawesome.json  
        reporter: mochawesome-json 

```
Build runner triggered manually:
```yml
- name: Create test report
      uses: phoenix-actions/test-reporting@v15
      if: success()
      with:
        name: 'build-tests-...matrix'
        fail-on-error: true
        path: mochawesome.json  
        reporter: mochawesome-json 
```
