### ISSUE TITLE
'list-tests: failed' still reporting successful tests.

### ISSUE THREAD

**Issue by siegfriedpammer** [phoenix-actions/test-reporting#7]
See https://github.com/dorny/test-reporter/issues/142

I would be willing to contribute the fix described in the above issue. However, I am very new to type-script and have no idea how to get started.

@IanMoroney Would it be possible for you to provide information on how to build/run this so I can try/add the suggested fix? Thanks!

**Comment by IanMoroney** [comment]
Looks like there's a linting problem in `get-report.ts`

As part of local development, if you run a `npm run all` it will include the `eslint` step.
I'll update the readme to include some local development steps 👍 

```
> eslint src/**/*.ts


/Users/work/Source/Repos/thirdparty/phoenix-test-reporting/src/report/get-report.ts
  235:17  error  Delete `;`       prettier/prettier
  235:17  error  Extra semicolon  semi
  235:17  error  Extra semicolon  @typescript-eslint/semi

✖ 3 problems (3 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the `--fix` option.
  ```

**Comment by IanMoroney** [comment]
you'll need to fix that issue in your branch before the CI run will succeed

**Comment by IanMoroney** [comment]
You can also run the `npm run format-check` command locally and if there's an issue from a `prettier` perspective, this should take care of it

**Comment by siegfriedpammer** [comment]
Thank you for pointing this out! I have fixed the issues and pushed an update.

**Comment by IanMoroney** [comment]
merged 👍

**Comment by IanMoroney** [comment]
https://github.com/phoenix-actions/test-reporting/releases/tag/v5

**Comment by siegfriedpammer** [comment]
Thank you for getting this merged... however, it doesn't seem to work in production...

see https://github.com/icsharpcode/ILSpy/runs/5464254493?check_suite_focus=true#step:12:7 (for the build output)
and https://github.com/icsharpcode/ILSpy/runs/5464619783#r0s7 (for the report)

I was expecting the output to just list the only test that I made fail for testing.

Not sure how I should begin to investigate the issue. Thank you for any help you can provide!

**Comment by IanMoroney** [comment]
Try https://github.com/phoenix-actions/test-reporting/releases/tag/v6
I noticed after I merged the code, and ran a fresh npm run all, that the dist hadn't been updated. I wonder if this could have had an effect on it.
Test again with v6, and if it's still not fixed, we can investigate 👍

**Comment by siegfriedpammer** [comment]
Thanks, seems to work now!

**Comment by sunnyoswalcro** [comment]
@IanMoroney facing same issue in :
```
- name: TEST-REPORTS-${{ github.job }}
      uses: phoenix-actions/test-reporting@v8
      if: always()
      with:
        name: TEST-REPORTS-${{ github.job }}     # Name of the check run which will be created
        path: build/root/test-results/*/*.xml    # Path to test results
        reporter: java-junit                     # Format of test results
        list-tests: 'failed'
        fail-on-error: 'false'
```
